### PR TITLE
Adapt to new `spatstat.random` package.

### PR DESCRIPTION
**Pull request by rubak**
Also weeded out hard dependencies on `spatstat` (which was never used) and `spatstat.core` which is only used in tests, vignettes and README, so it can be optional (in `Suggests`). As far as I can see all functions from `envi` work without `spatstat.core` installed.

When `spatstat` (or `spatstat.core`) was in `Depends` it implied that whenever you loaded `envi` then `spatstat` (and hence `spatstat.core`, `spatstat.geom`, ...). This means that it was obsolete to write first `library(envi)` and then `library(spatstat.core)` afterwards. In case `envi` would never be used without also loading `spatstat` (or `spatstat.core`) you may of course reinstate this feature.

Feel free to ask if any of this is unclear.

### CODE REVIEW

**Comment by idblr** [comment]
Thanks, @rubak! I appreciate your (and the spatstat team) time and energy to help a new(er) developer. 

I also manage the [sparrpowR package](https://github.com/machiela-lab/sparrpowR) so I suspect some similar issues.

**Comment by idblr** [comment]
Hi @rubak, I see you made a similar merge request for the sparrpowR package (https://github.com/machiela-lab/sparrpowR/commit/6bbdea5cf24642769b9c5e573de0d362903fdfec) and noticed you listed `spatstat.core` in Suggets here for 'envi' but listed `spatstat (>= 2.0-0)` in Suggest for 'sparrpowR'

Any particular reason for the discrepancy? Thanks for all the assistance.

**Comment by rubak** [comment]
Here in `envi` you always seem to load `spatstat.core` explicitly rather than the umbrella `spatstat` package (which would also load `spatstat.linnet`). Then it seems logical that you suggest the package that you actually use. In `sparrpowR` you call `library(spatstat)`, so it is natural to have that in `Suggests`. However, I now see that the `library(spatstat)` call in `sparrpowR` is in a file called `dev/hexSticker_sparrpowR.R`, so it is probably not really a part of the package and you don't need to suggest `spatstat` (I don't even think you need to suggest `spatstat.core`).

Typically `Suggests` is used for a package that is only needed for a single function in your package which is not so important, but more of an extra feature. So it is feasible to install and use your package without the suggested package, and there is only a single function that wouldn't work. This function would test for the presence of the suggested package and exit with an informative message if it is not installed.

You use `spatstat`/`spatstat.core` a bit differently since it is mostly used in tests of your package (and possibly as examples in README, but that is not really part of the official package either). So installing them really doesn't add any functionality to your package, and you could say that they are not needed at all. Also the usual practice of checking whether the suggested package is installed before using it (which you don't do) is maybe not necessary here. The only unfortunate thing with your packages is that if you install them and only the required dependencies you will get a failure when trying to run `R CMD check` since they try to load `spatstat`/`spatstat.core` during tests. The way around this would be to wrap the relevant tests in 
```r
if(requireNamespace(spatstat.core){
# Run tests as usual
} else{
mesasge("Test skipped since spatstat.core is not installed")
}
```
but I think this might be overkill since it is only tests that fail and not actual user examples/functions.

**Comment by idblr** [comment]
Thanks @rubak! This rundown is helpful. I ran through each package and listed the appropriate Suggests. The `dev` directories and README are ignored by CRAN so it makes sense to remove the packages used therein from the CRAN submission. Thank you for thoroughly reviewing my code. Fingers crossed for CRAN checks. If not, I will try your 'overkill' suggestion.

**Comment by idblr** [comment]
Hi @rubak. I recently pushed an updated version of this package to CRAN and three environments have ERROR in the [CRAN Package Check Results](https://cran.r-project.org/web/checks/check_results_envi.html).

r-devel-linux-x86_64-debian-gcc 
r-devel-windows-x86_64-new-UL
r-release-linux-x86_64

The [error](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/envi-00install.html) appears to be same in these environments relating to:

```
Error: object ‘is.poisson’ not found whilst loading namespace ‘spatstat.linnet’
Execution halted
```

I no longer have the `spatstat.linnet` package as a dependency, based on your recommendation in this pull request. Can you advise on a solution? Are you seeing this in other reverse dependencies?

Thanks!

**Comment by rubak** [comment]
Hi @idblr this is indeed confusing. The error actually comes from `sparr`, and when you have `importFrom(sparr, ...)` in your NAMESPACE your package tries to load `sparr` which then gives an error/warning. The error from `sparr` comes from spatstat.xxxx being updated before `sparr`. Hopefully it will be updated one of the next days and everything should automatically go back to normal 🤞

**Comment by idblr** [comment]
Thanks, @rubak! I'll watch how it unfolds.

**Pull request merged**
